module.exports = {
  STATUS_CREATED: 201,
  STATUS_OK: 200,
  STATUS_BAD_REQUEST: 400,
  STATUS_UNAUTHORIZED: 401,
  STATUS_NOT_FOUND: 404,
  STATUS_INTERNAL_SERVER_ERROR: 500,
  STATUS_UNPROCCESSABLE_ENTITIY: 422,
};
